FROM node:18-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .env ./

COPY backend ./backend
COPY frontend ./frontend
COPY artifacts ./artifacts

EXPOSE 3000

# Start backend server
CMD ["node", "backend/server.js"]
