FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .env ./

COPY iot-simulator ./iot-simulator

# Wait for backend to be ready before starting
CMD ["sh", "-c", "sleep 15 && node iot-simulator/simulator.js"]
